### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'commentId')

### ISSUE THREAD

**Issue by astepforward** [umnik1/dtfPrize#1]
#### Ошибка
После выставления определённых настроек розыгрыша и нажатия кнопки "Определить победителя" результаты розыгрыша не отображаются. В консоли появляется ошибка:
![image](https://user-images.githubusercontent.com/9438336/219911234-2e74ed30-2803-4add-a73f-a45270e870a8.png)

#### Настройки розыгрыша для воспроизведения
![image](https://user-images.githubusercontent.com/9438336/219910959-34f9f6e9-9b15-4cb0-99a7-ff7703c6a3af.png)
Ссылка на пост со скрина: https://dtf.ru/flood/1418283

Воспроизводится на разных вариантах настроек. Один раз воспроизвелось при выставленном одном победителе с остальными настройками со скрина.

**Comment by umnik1** [comment]
Спасибо, поправил.
